import random
numero1 = random.randint(0, 9)
numero2 = random.randint(0, 9)
numero3 = random.randint(0, 9)
print("Kolminumeroinen koodisi on:", str(numero1) + str(numero2) + str(numero3))
num1 = random.randint(0, 6)
num2 = random.randint(0, 6)
num3 = random.randint(0, 6)
num4 = random.randint(0, 6)
print("Nelinumeroinen koodisi on:", str(num1) + str(num2) + str(num3) + str(num4))